# instalacion de las dependencias de nodejs
FROM node:22-alpine AS dev-deps
WORKDIR /app
COPY package.json package.json
RUN npm install -g pnpm
RUN pnpm install


# ejecucion del programa en un entorno de desarrollo
FROM node:22-alpine AS dev
WORKDIR /app
COPY --from=dev-deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD npm run dev
