services:
# DATABASE
  mariadb:
    image: mariadb:11-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  # phpmyadmin:
  #   depends_on:
  #     - mariadb
  #   image: phpmyadmin:apache
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - PMA_HOST=mariadb


# FRONTEND
  backend:
    depends_on:
      - mariadb
    build: ./backend
    ports:
      - "8000:8000"
      - "8080:8080"
      - "4000:4000"


# FRONTEND
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
