services:
# DATABASE
  mariadb:
    container_name: mariadb
    image: mariadb:11-jammy
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./backend/structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data:/var/lib/mysql


# BACKEND
  backend:
    container_name: backend
    depends_on:
      - mariadb
    build: ./backend
    ports:
      - "8000:8000"
      - "8080:8080"
      - "4000:4000"


# FRONTEND
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "3000:3000"
