services:
# FRONTEND
  nodejs-frontend:
    working_dir: /app
    image: node:22-alpine
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


# BACKEND
  mariadb:
    image: mariadb:11-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  nodejs-backend:
    depends_on:
      - mariadb
    working_dir: /app
    image: node:22-alpine
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin:apache
    ports:
      - "80:80"
    environment:
      - PMA_HOST=${DATABASE_HOST}
