services:
  mariadb:
    image: mariadb:11-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./../db/data:/var/lib/mysql

  nodejs:
    depends_on:
      - mariadb
    working_dir: /app
    image: node:22-alpine
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - "80:80"
    environment:
      - PMA_HOST=${DATABASE_HOST}
