DROP DATABASE IF EXISTS sansi_web;
CREATE DATABASE sansi_web;
USE sansi_web;


CREATE TABLE USUARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  correo_electronico CHAR(23) NOT NULL UNIQUE,
  nombre VARCHAR(30) NOT NULL,
  apellido_paterno VARCHAR(30),
  apellido_materno VARCHAR(30),
  numero_celular VARCHAR(20) NOT NULL UNIQUE,
  foto_perfil VARCHAR(255) NOT NULL,
  fecha_creacion TIMESTAMP NOT NULL DEFAULT (NOW()),
  PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
  ID INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTENIDO (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_usuario INT NOT NULL,
  descripcion TEXT NOT NULL,
  fecha_publicacion TIMESTAMP NOT NULL DEFAULT (NOW()),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_usuario) REFERENCES USUARIO(ID)
);

CREATE TABLE TEMA (
  ID INT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES CONTENIDO(ID)
);

CREATE TABLE COMENTARIO (
  ID INT NOT NULL,
  ID_tema INT NOT NULL,
  destacado BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES CONTENIDO(ID),
  FOREIGN KEY (ID_tema) REFERENCES TEMA(ID)
);

CREATE TABLE ME_INTERESA (
  ID_contenido INT NOT NULL,
  ID_usuario INT NOT NULL,
  fecha TIMESTAMP NOT NULL DEFAULT (NOW()),
  PRIMARY KEY (ID_contenido, ID_usuario),
  FOREIGN KEY (ID_contenido) REFERENCES CONTENIDO(ID),
  FOREIGN KEY (ID_usuario) REFERENCES USUARIO(ID)
);

CREATE TABLE GUARDADO (
  ID_contenido INT NOT NULL,
  ID_usuario INT NOT NULL,
  fecha TIMESTAMP NOT NULL DEFAULT (NOW()),
  PRIMARY KEY (ID_contenido, ID_usuario),
  FOREIGN KEY (ID_contenido) REFERENCES CONTENIDO(ID),
  FOREIGN KEY (ID_usuario) REFERENCES USUARIO(ID)
);

CREATE TABLE R_TEMA_CATEGORIA (
  ID_tema INT NOT NULL,
  ID_categoria INT NOT NULL,
  PRIMARY KEY (ID_tema, ID_categoria),
  FOREIGN KEY (ID_tema) REFERENCES TEMA(ID),
  FOREIGN KEY (ID_categoria) REFERENCES CATEGORIA(ID)
);

CREATE TABLE VISUALIZACION (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_tema INT NOT NULL,
  ID_usuario INT NOT NULL,
  fecha_visualizacion TIMESTAMP NOT NULL DEFAULT (NOW()),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_tema) REFERENCES TEMA(ID),
  FOREIGN KEY (ID_usuario) REFERENCES USUARIO(ID)
);




